# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63onsensus_message.proto\x12\rsawtooth_dpos\"\x12\n\x10\x43onsensusMessageb\x06proto3')



_CONSENSUSMESSAGE = DESCRIPTOR.message_types_by_name['ConsensusMessage']
ConsensusMessage = _reflection.GeneratedProtocolMessageType('ConsensusMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSMESSAGE,
  '__module__' : 'consensus_message_pb2'
  # @@protoc_insertion_point(class_scope:sawtooth_dpos.ConsensusMessage)
  })
_sym_db.RegisterMessage(ConsensusMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONSENSUSMESSAGE._serialized_start=42
  _CONSENSUSMESSAGE._serialized_end=60
# @@protoc_insertion_point(module_scope)
