# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consensus_message.proto',
  package='sawtooth_dpos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63onsensus_message.proto\x12\rsawtooth_dpos\"\x12\n\x10\x43onsensusMessageb\x06proto3'
)




_CONSENSUSMESSAGE = _descriptor.Descriptor(
  name='ConsensusMessage',
  full_name='sawtooth_dpos.ConsensusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['ConsensusMessage'] = _CONSENSUSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConsensusMessage = _reflection.GeneratedProtocolMessageType('ConsensusMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSMESSAGE,
  '__module__' : 'consensus_message_pb2'
  # @@protoc_insertion_point(class_scope:sawtooth_dpos.ConsensusMessage)
  })
_sym_db.RegisterMessage(ConsensusMessage)


# @@protoc_insertion_point(module_scope)
